Fix undefined showing up in output of hexFormat
andrasq/node-mongoid-js pull request #6
Opened 2017-08-25 19:44 UTC by cwohlman

Fixes #5 

Note, on my machine there are still 2 failing tests:

```
AssertionError: false is 'truthy'
    at Object.id should include pid (/Users/joshuaohlman/dev/node-mongoid-js/test/test-mongoid.js:155:11)
    at /Users/joshuaohlman/dev/node-mongoid-js/node_modules/qnit/lib/qnit.js:397:32
    at /Users/joshuaohlman/dev/node-mongoid-js/node_modules/aflow/lib/qflow.js:109:13
    at _invokeCallback (/Users/joshuaohlman/dev/node-mongoid-js/node_modules/aflow/lib/qflow.js:49:20)
    at applyFunc (/Users/joshuaohlman/dev/node-mongoid-js/node_modules/aflow/lib/qflow.js:103:50)
    at _loop (/Users/joshuaohlman/dev/node-mongoid-js/node_modules/aflow/lib/qflow.js:62:13)
    at repeatUntil (/Users/joshuaohlman/dev/node-mongoid-js/node_modules/aflow/lib/qflow.js:72:5)
    at Object.applyVisitor (/Users/joshuaohlman/dev/node-mongoid-js/node_modules/aflow/lib/qflow.js:101:5)
    at runit (/Users/joshuaohlman/dev/node-mongoid-js/node_modules/qnit/lib/qnit.js:369:15)
    at runTestFunction (/Users/joshuaohlman/dev/node-mongoid-js/node_modules/qnit/lib/qnit.js:352:5)

 X MongoId_class - testShouldParseId (1.115ms)

AssertionError: 5700 == 91208
    at Object.testShouldParseId (/Users/joshuaohlman/dev/node-mongoid-js/test/test-mongoid.js:194:14)
    at /Users/joshuaohlman/dev/node-mongoid-js/node_modules/qnit/lib/qnit.js:397:32
    at /Users/joshuaohlman/dev/node-mongoid-js/node_modules/aflow/lib/qflow.js:109:13
    at _invokeCallback (/Users/joshuaohlman/dev/node-mongoid-js/node_modules/aflow/lib/qflow.js:49:20)
    at applyFunc (/Users/joshuaohlman/dev/node-mongoid-js/node_modules/aflow/lib/qflow.js:103:50)
    at _loop (/Users/joshuaohlman/dev/node-mongoid-js/node_modules/aflow/lib/qflow.js:62:13)
    at repeatUntil (/Users/joshuaohlman/dev/node-mongoid-js/node_modules/aflow/lib/qflow.js:72:5)
    at Object.applyVisitor (/Users/joshuaohlman/dev/node-mongoid-js/node_modules/aflow/lib/qflow.js:101:5)
    at runit (/Users/joshuaohlman/dev/node-mongoid-js/node_modules/qnit/lib/qnit.js:369:15)
    at runTestFunction (/Users/joshuaohlman/dev/node-mongoid-js/node_modules/qnit/lib/qnit.js:352:5)

```

2017-08-30 14:30 UTC, andrasq requested changes
the tests are failing because is uses the actual process id which didn't fit into the generated mongoid.  When the id is clipped with `substr` the original id will not be found in the mongoid, nor is it recoverable with parseId.

Should also have a test to check that the change is working (ie, that the generated mongoid is valid when the process id is longer than 16 bits)

2017-08-30 14:30 UTC, andrasq commented on mongoid.js
> +    if (paddingNeeded > 0) {
this could be simpler written as `if (s.length <= width)`

2017-08-30 14:30 UTC, andrasq commented on mongoid.js
> +        return s.substr(0, width);
for most id fields keeping the least significant bits would preserve uniqueness better (ie, for all the incrementing fields like process id), so maybe `return s.substr(-width)`.  In this case it is the process id that was too long.

Note that with a clipped process id it's not possible to guarantee uniqueness (well, one could formulate a "machine id" that preserved the process uniqueness I suppose)

2017-08-30 14:35 UTC, cwohlman commented
Thanks for the feedback. I'll update the PR when I get a chance.

Question: do you think there's any other way to solve the problem than clipping the process id?

2017-08-30 14:59 UTC, andrasq commented
the problem is that a mongoid uses 16 bits to store the process id, but it seems some systems use process ids longer than 16 bits.

The extra bits can be discarded (clipped), they can be disallowed (throw an error if the process id is too big), or can be stuffed into one of the other fields.  It would be a non-standard mongoid, but would parse as valid and would preserve uniqueness.

Stuffing the extra bits into the machine id wouldn't even require changing the code, just a properly constructed system id to the constructor, eg:

```
// 20 random bits followed by the 4 high bits of the process id
const machineId = (Math.floor(Math.random() *  (1 << 20)) << 4) + ((process.pid >> 16) & 0xF);
var mongoid = new Mongoid(machineId);
```

2017-08-30 15:07 UTC, andrasq commented
the split process id and hacked system id handling could be moved into mongoid-js I guess, I'll have to think about that one.  parse() would have to be aware of it too, but none of the changes should affect the critical path.

2017-08-30 15:21 UTC, andrasq commented on mongoid.js
> +    if (paddingNeeded > 0) {
or even simpler if the incoming process id is masked first, ie
`this.processIdStr = hexFormat(machineId, 6) + hexFormat(processId & 0xFFFF, 4);`
(the other formatted fields, timestamp, sequence and machineId, are already length checked)

2017-08-30 17:59 UTC, andrasq commented
This won't work in all cases.  The linux `kernel.pid_max` can be configured up to 31 bits, whereas the trick above only saves 4 more bits.

2017-08-30 18:17 UTC, cwohlman commented
Hm... I guess I'll just make the changes you originally suggested for now. It sounds like trying to support larger process ids will mean more complexity without fully solving the problem.

2017-09-14 21:38 UTC, andrasq commented
I merged in PR #7 that should fix the broken ids that included "undefined" in the id string and fixes the unit tests that sometimes failed on systems with 17 bit and longer process ids.

A more "clever" way of supporting longer process ids would be more complex, would not be portable (ie only mongoid-js would know how to recover the full pid from an id string), and would only add a few additional bits of process id precision.  The linux `kernel.pid_max` can be configured to max 2 ^ 22, ie 22 bits.

2017-09-15 20:26 UTC, cwohlman commented
Closing since #7 fixes this issue.

2017-09-15 20:26 UTC, closed without merging